/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCPosixTaskLaunchInfo.h>

@class XCDistributedBuildHost;

@interface _XCDistributedBuildHostInfoTaskLaunchInfo : XCPosixTaskLaunchInfo
{
    XCDistributedBuildHost *_host;
}

- (id)buildHost;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setBuildHost:(id)arg1;

@end

