/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface PBXBuildMessage : NSObject
{
    int _type;
    NSString *_messageString;
    NSArray *_fileLocations;
    unsigned long long _buildLogItemIdentifier;
    NSMutableArray *_submessages;
}

+ (id)buildErrorMessageWithFormat:(id)arg1;
+ (id)buildNoticeMessageWithFormat:(id)arg1;
+ (id)buildWarningMessageWithFormat:(id)arg1;
- (void)addSubmessage:(id)arg1;
@property(nonatomic) unsigned long long buildLogItemIdentifier; // @synthesize buildLogItemIdentifier=_buildLogItemIdentifier;
- (void)dealloc;
- (id)description;
- (id)fileLocations;
- (id)filePath;
- (id)initWithType:(int)arg1 messageString:(id)arg2;
- (id)initWithType:(int)arg1 messageString:(id)arg2 fileLocations:(id)arg3;
- (BOOL)isAnalyzerResult;
- (BOOL)isError;
- (BOOL)isNotice;
- (BOOL)isWarning;
- (unsigned long long)lineNumber;
- (id)messageString;
- (void)setFileLocations:(id)arg1;
- (void)setMessageString:(id)arg1;
- (id)submessages;
- (int)type;

@end

