/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXBuildPhase.h>

@class NSString;

@interface PBXCopyFilesBuildPhase : PBXBuildPhase
{
    int _dstSubfolderSpec;
    NSString *_dstPath;
}

+ (id)archivableAttributes;
+ (id)defaultName;
+ (id)identifier;
- (BOOL)acceptsVariantGroups;
- (id)allowedFileTypes;
- (unsigned int)appleScriptDestinationSubfolder;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (BOOL)canRename;
- (void)dealloc;
- (Class)dependencyGraphSnapshotClass;
- (id)destinationPath;
- (int)destinationSubfolder;
- (id)initFromTemplateDictionary:(id)arg1;
- (id)initWithName:(id)arg1;
- (void)setAbsolutePath:(id)arg1;
- (void)setAppleScriptDestinationSubfolder:(unsigned int)arg1;
- (void)setDestinationPath:(id)arg1;
- (void)setDestinationSubfolder:(int)arg1;
- (void)setSubpath:(id)arg1 relativeToSubfolder:(int)arg2;

@end

