/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol PBXCompletionItem
- (id)completionText;
- (id)descriptionText;
- (id)displayText;
- (id)displayType;
- (id)icon;
- (id)name;
- (long long)priority;
@end

