/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXMemberContainerSymbol.h>

@interface PBXClassSymbol : PBXMemberContainerSymbol
{
}

+ (BOOL)canRepresentSymbolType:(int)arg1;
- (id)allSuperclasses;
- (BOOL)canHaveCategories;
- (id)categories;
- (id)displayNameIncludingClassInfo:(BOOL)arg1;
- (id)extensions;
- (id)helpMarkerSymbolType;
- (id)helpMarkerSymbolValue;
- (id)immediateSuperclasses;
- (id)subclassesIncludingIndirect:(BOOL)arg1;
- (id)superclassesIncludingIndirect:(BOOL)arg1;
- (id)typeString;

@end

