/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, PBXCCType, PBXSymbol;

@interface PBXCCSymbol : NSObject
{
    NSString *name;
    PBXCCType *ccType;
    PBXSymbol *pbxSymbol;
    long long priority;
}

+ (id)symbolWithName:(id)arg1 ccType:(id)arg2;
+ (id)symbolWithName:(id)arg1 unresolvedSymbol:(id)arg2 ccType:(id)arg3;
- (void)addIndirection;
- (id)ccType;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)initWithName:(id)arg1 unresolvedSymbol:(id)arg2 ccType:(id)arg3;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (id)pbxSymbol;
- (long long)priority;
- (void)setPriority:(long long)arg1;
- (id)typeName;

@end

