/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXIndexingEngine.h>

@interface PBXDevKitIndexingEngine : PBXIndexingEngine
{
    struct NXNamedStream *_inputStream;
    struct Lex *_lex;
    struct PBXIndexCppActions *_cppActions;
    struct Cpp *_cpp;
    struct PBXIndexCParseActions *_parseActions;
    struct ObjcParse *_parser;
    struct StringTable *_stringTable;
}

+ (id)indexableFileTypes;
+ (void)initialize;
- (void)_cppInitialize:(struct Cpp *)arg1 settings:(id)arg2;
- (void)beginIndexingPass;
- (void)cancel;
- (void)defineClass:(const char *)arg1 cplus:(BOOL)arg2;
- (void)defineMacro:(const char *)arg1 expansion:(const char *)arg2;
- (void)defineTemplate:(const char *)arg1;
- (void)defineType:(const char *)arg1;
- (void)endIndexingPass;
- (void)indexFileAtAbsolutePath:(id)arg1 withSettings:(id)arg2;
- (void)stopIndexing;
- (BOOL)wantsImportedSymbols;

@end

