/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXBookmark.h>

@class PBXExecutable;

@interface PBXExecutableBookmark : PBXBookmark
{
    PBXExecutable *_executable;
}

+ (id)archivableRelationships;
+ (id)archiveNameForKey:(id)arg1;
- (void)dealloc;
- (id)defaultName;
- (id)executable;
- (unsigned long long)hash;
- (id)initWithExecutable:(id)arg1;
- (id)initWithFileReference:(id)arg1;
- (id)innerDescription;
- (BOOL)isEqual:(id)arg1;

@end

