/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSEnumerator.h"

#import "NSCopying-Protocol.h"

@class NSMutableArray;

@interface PBXGroupEnumerator : NSEnumerator <NSCopying>
{
    NSMutableArray *_enumeratedObjects;
    unsigned long long _nextIndex;
    unsigned long long _count;
}

+ (id)enumeratorForGroup:(id)arg1;
+ (id)enumeratorForGroup:(id)arg1 startingAtItem:(id)arg2;
+ (SEL)traversalSelector;
- (id)allObjects;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)firstObject;
- (id)initWithRootArray:(id)arg1 nextObject:(id)arg2;
- (id)lastObject;
- (id)nextObject;
- (unsigned long long)numberOfObjects;
- (id)previousObject;
- (void)rewind;
- (void)setNextObject:(id)arg1;

@end

