/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class PBXObject;

@interface PBXGlobalID : NSObject <NSCopying>
{
    unsigned char _bytes[12];
    PBXObject *_theObject;
}

+ (void)initialize;
+ (void)setCachesHexStrings:(BOOL)arg1;
- (void)_cacheHexString:(id)arg1;
- (id)_cachedHexString;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)hexString;
- (id)init;
- (id)initWithHexString:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;

@end

