/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXTarget.h>

@interface PBXJambaseTarget : PBXTarget
{
}

+ (id)buildSystemDefaultBuildSettings;
+ (id)buildSystemDefaultBuildSettings_asPropertyValues;
+ (id)jambasePath;
+ (id)jambasePlatformFilePath;
- (BOOL)buildSettingsDictionaryShouldExtractQuotedBuildSettingsWhenSplitting:(id)arg1;
- (id)commandsForCleaningInBuildContext:(id)arg1;
- (Class)dependencyGraphSnapshotClass;
- (BOOL)shouldWriteAuxiliaryFilesForBuildAction:(id)arg1;

@end

