/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXMemberSymbol.h>

@interface PBXMemberVariableSymbol : PBXMemberSymbol
{
}

+ (BOOL)canRepresentSymbolType:(int)arg1;
- (BOOL)displayNameAllowsIndent;
- (id)displayNameIncludingClassInfo:(BOOL)arg1;
- (id)helpMarkerSymbolType;
- (id)helpMarkerSymbolValue;
- (BOOL)isClassMember;
- (BOOL)isInstanceMember;

@end

