/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PBXSourceLexer;

@interface PBXSourceScanner : NSObject
{
    PBXSourceLexer *_lexer;
}

- (void)dealloc;
- (void)initInterestingSymbols;
- (void)initSourceLexerForSpecification:(id)arg1;
- (id)initWithLanguageSpecification:(id)arg1;
- (id)lexer;
- (id)parse;
- (id)parseString:(id)arg1;

@end

