/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXProject.h>

@class NSMutableArray, NSMutableDictionary, XCProductTypeSpecification;

@interface PBXStandaloneTarget : PBXProject
{
    XCProductTypeSpecification *_productType;
    NSMutableDictionary *_buildProperties;
    NSMutableArray *_buildRules;
}

+ (id)archivableAttributes;
+ (id)archivableRelationships;
- (id)_productType;
- (void)_setProductType:(id)arg1;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (void)dealloc;
- (id)init;

@end

