/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface PBXStringTreeNode : NSObject
{
    NSString *_string;
    PBXStringTreeNode *_nextSibling;
    PBXStringTreeNode *_firstChild;
    id _representedObject;
}

+ (id)nodeWithString:(id)arg1 representedObject:(id)arg2;
- (void)addSubnode:(id)arg1;
- (void)addSubnode:(id)arg1 sorted:(BOOL)arg2;
- (void)addSubnode:(id)arg1 sorted:(BOOL)arg2 sortHint:(id)arg3;
- (void)dealloc;
- (id)description;
- (unsigned long long)indexOfSubnode:(id)arg1;
- (id)init;
- (id)initWithString:(id)arg1 representedObject:(id)arg2;
- (BOOL)isLeaf;
- (unsigned long long)numSubnodes;
- (void)removeSubnode:(id)arg1;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;
- (void)setString:(id)arg1;
- (id)string;
- (id)subnodeAtIndex:(unsigned long long)arg1;
- (id)subnodeWithString:(id)arg1;
- (id)subnodes;
- (id)treeDescriptionWithPrefix:(id)arg1;

@end

