/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXJambaseTarget.h>

@interface PBXToolTarget : PBXJambaseTarget
{
}

+ (id)categorizedTargetName;
+ (id)standardBuildPhaseClasses;
+ (id)targetTypeDisplayName;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (id)defaultProductTypeIdentifierByAnalyzingConfiguration;
- (BOOL)isJavaProduct;
- (id)productReferenceExpectedFileTypeForConfigurationNamed:(id)arg1;
- (BOOL)productReferenceIsExecutable;
- (BOOL)wantsProductSettings;

@end

