/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SCMBasePathObject : NSObject
{
    NSString *_basePath;
}

- (id)absolutePathForModelPath:(id)arg1;
- (id)absolutePathsForModelPaths:(id)arg1;
- (id)absolutePathsForNodes:(id)arg1;
- (id)basePath;
- (void)dealloc;
- (id)init;
- (id)modelPathForAbsolutePath:(id)arg1;
- (id)modelPathsForAbsolutePaths:(id)arg1;
- (id)pathsForNodes:(id)arg1;
- (void)setBasePath:(id)arg1;

@end

