/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/SCMNode.h>

@class NSDictionary, SCMLog;

@interface SCMDirectoryEntry : SCMNode
{
    NSDictionary *_info;
    SCMLog *_log;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)children;
- (id)createChildWithName:(id)arg1;
- (void)dealloc;
- (void)finishInfo:(id)arg1;
- (void)finishList:(id)arg1;
- (id)info;
- (id)initWithModel:(id)arg1 parent:(id)arg2 name:(id)arg3 isDirectory:(BOOL)arg4;
- (BOOL)isLeaf;
@property(retain) SCMLog *log; // @synthesize log=_log;
- (id)myself;
- (void)setInfo:(id)arg1;

@end

