/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCRoots.h>

@class NSMutableDictionary;

@interface SCMRootToRepositoryMap : XCRoots
{
    NSMutableDictionary *_rootsToRepositories;
}

- (void)addRoot:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1 project:(id)arg2;
- (BOOL)pathsOnSameVolume:(id)arg1;
- (void)removeRoot:(id)arg1;
- (id)repositoryForRoot:(id)arg1;
- (id)repositoryNameForRoot:(id)arg1;
- (id)roots;
- (void)setRepositoryClass:(Class)arg1;
- (void)setRepositoryName:(id)arg1 forRoot:(id)arg2;

@end

