/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSNumber, NSString;

@interface SCMRevision : NSObject <NSCopying>
{
    int _kind;
    NSNumber *_number;
    NSDate *_date;
    NSString *_string;
}

+ (void)initialize;
+ (id)revisionBASE;
+ (id)revisionSTART;
+ (id)revisionTOT;
+ (id)revisionUNSPECIFIED;
+ (id)revisionWORKING;
+ (id)revisionWithDate:(id)arg1;
+ (id)revisionWithNumber:(id)arg1;
+ (id)revisionWithString:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain) NSDate *date; // @synthesize date=_date;
- (void)dealloc;
- (id)description;
- (id)initWithType:(int)arg1;
@property int kind; // @synthesize kind=_kind;
@property(retain) NSNumber *number; // @synthesize number=_number;
@property(copy) NSString *string; // @synthesize string=_string;
@property(readonly) NSString *stringValue;
@property(readonly) id value;

@end

