/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SFCertificateData.h"

@interface SFCertificateData (XCCertificateDataExtensions)
- (id)_XCInfoAtIndex:(unsigned long long)arg1;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)longDescription;
- (id)name;
@end

