/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface XCAppleScriptBuildSetting : NSObject
{
    NSString *_name;
    NSString *_tempValue;
    id _container;
}

- (id)container;
- (void)dealloc;
- (id)init;
- (id)initWithName:(id)arg1 andContainer:(id)arg2;
- (id)name;
- (id)objectSpecifier;
- (void)setContainer:(id)arg1;
- (void)setName:(id)arg1;
- (void)setValue:(id)arg1;
- (id)value;

@end

