/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PBXBuildFile;

@interface XCAppleScriptBuildMessage : NSObject
{
    PBXBuildFile *_buildFile;
    long long _index;
}

- (id)buildFile;
- (void)dealloc;
- (id)filePath;
- (long long)index;
- (id)init;
- (unsigned long long)lineNumber;
- (id)messageString;
- (id)objectSpecifier;
- (void)setBuildFile:(id)arg1;
- (void)setIndex:(long long)arg1;
- (unsigned int)type;

@end

