/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSSet, NSString;

@interface XCArchiveFormat : NSObject
{
    NSString *_identifier;
    NSString *_minimumVersionSupported;
    unsigned long long _versionNumberForArchiver;
    NSSet *_supportedFeatures;
    NSSet *_archivingTranslations;
}

- (id)archivingTranslations;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (id)displayName;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithArchiverVersion:(unsigned long long)arg1 identifier:(id)arg2 minimumVersionSupportedName:(id)arg3 supportedFeatures:(id)arg4 archivingTranslations:(id)arg5;
- (BOOL)isEqual:(id)arg1;
- (id)minimumVersionSupportedName;
- (id)supportedFeatures;
- (unsigned long long)versionNumberForArchiver;

@end

