/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet, NSSet, NSString, XCArchivedApplicationBuild;

@interface XCArchivedApplication : NSObject
{
    NSString *_bundleIdentifier;
    NSString *_platformIdentifier;
    NSMutableSet *_applicationBuilds;
    unsigned int _hasPlatformConflict:1;
}

+ (id)appWithBundleIdentifier:(id)arg1 andPlatformIdentifier:(id)arg2;
+ (id)keyPathsForValuesAffectingApplicationName;
+ (id)keyPathsForValuesAffectingApplicationVersion;
+ (id)keyPathsForValuesAffectingLatestBuild;
- (void)addApplicationBuildsObject:(id)arg1;
@property(readonly) NSSet *applicationBuilds;
@property(readonly) NSString *applicationName;
@property(readonly) NSString *applicationVersion;
@property(copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (id)description;
@property _Bool hasPlatformConflict; // @synthesize hasPlatformConflict=_hasPlatformConflict;
- (unsigned long long)hash;
- (id)init;
- (BOOL)isEqual:(id)arg1;
@property(readonly) XCArchivedApplicationBuild *latestBuild;
- (id)memberOfApplicationBuilds:(id)arg1;
- (id)mutableApplicationBuilds;
@property(readonly) NSString *platformDisplayName;
@property(copy) NSString *platformIdentifier; // @synthesize platformIdentifier=_platformIdentifier;
- (void)removeApplicationBuildsObject:(id)arg1;
- (id)sortedApplicationBuilds;

@end

