/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCAttributeRunIndirectNode.h>

@interface XCAttributeRun : XCAttributeRunIndirectNode
{
}

+ (void)initialize;
+ (void)performSelfTest;
+ (void)selfTestFailure:(id)arg1 attributeRun:(id)arg2 iteration:(unsigned long long)arg3;
+ (BOOL)selfTestWithRunLength:(unsigned long long)arg1 iterations:(unsigned long long)arg2 numAttrs:(unsigned long long)arg3 maxAttributeLength:(unsigned long long)arg4 coalesce:(BOOL)arg5;
- (void *)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (void)deleteRange:(struct _NSRange)arg1;
- (id)init;
- (id)initWithObjectAttributes:(BOOL)arg1 coalescesAttributes:(BOOL)arg2;
- (void)insertAttributes:(void *)arg1 range:(struct _NSRange)arg2;
- (void)setAttributes:(void *)arg1 range:(struct _NSRange)arg2;
- (id)split;

@end

