/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCBuildLogMessage.h>

@class NSString;

@interface XCBuildLogAnalyzerResultMessage : XCBuildLogMessage
{
    NSString *_resultType;
}

- (void)dealloc;
- (id)initFromDeserializer:(id)arg1;
- (BOOL)isAnalyzerResult;
- (BOOL)isAnalyzerResultMessage;
- (id)resultCategory;
- (id)resultType;
- (void)setResultType:(id)arg1;
- (void)writeToSerializer:(id)arg1;

@end

