/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class XCBuildConfiguration;

@interface XCBuildConfigurationType : NSObject
{
    XCBuildConfiguration *_configuration;
    BOOL _isCopy;
}

- (id)appleScriptID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithConfiguration:(id)arg1;
- (BOOL)isCopy;
- (id)name;
- (id)objectSpecifier;
- (void)setIsCopy:(BOOL)arg1;
- (void)setName:(id)arg1;

@end

