/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCBuildOperation.h>

@class NSMapTable;

@interface XCBuildResultsRestoreOperation : XCBuildOperation
{
    NSMapTable *_restoreInfoByBuildable;
    BOOL _someResultsWereRestored;
}

- (void)_cleanupAfterRunning;
- (BOOL)_setupBeforeRunning;
- (BOOL)buildDependencies;
- (void)cancel;
- (int)cleanupAfterRunning;
- (void)dealloc;
- (id)initWithProject:(id)arg1 buildAction:(id)arg2 configurationName:(id)arg3 activeArchitecture:(id)arg4 overridingProperties:(id)arg5 buildables:(id)arg6;
- (BOOL)isBuildResultsRestoreOperation;
- (BOOL)isReadyToRunWithReasonForDelay:(id *)arg1;
- (int)runOperationInBackground;
- (int)setupBeforeRunning;
- (BOOL)shouldDisplaySummaryInBuildLog;

@end

