/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class XCTextFileLocation;

@interface XCBuildLogAnalyzerControlFlowStepEdge : NSObject
{
    XCTextFileLocation *_startFileLocation;
    XCTextFileLocation *_endFileLocation;
}

- (void)dealloc;
- (id)description;
- (id)endFileLocation;
- (id)initFromDeserializer:(id)arg1;
- (id)initWithStartLocation:(id)arg1 endLocation:(id)arg2;
- (id)startFileLocation;
- (void)writeToSerializer:(id)arg1;

@end

