/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, XCBuildStateStore;

@interface XCBuildStateStoreEntry : NSObject
{
    XCBuildStateStore *_store;
    NSString *_ident;
}

- (id)buildStateStore;
- (void)dealloc;
- (id)description;
- (id)identifier;
- (id)init;
- (id)initFromFileHandle:(struct __sFILE *)arg1 withIdentifier:(id)arg2 inBuildStateStore:(id)arg3;
- (id)initWithIdentifier:(id)arg1 inBuildStateStore:(id)arg2;
- (void)invalidate;
- (BOOL)isValid;
- (id)longDescription;
- (void)readPropertiesFromFileHandle:(struct __sFILE *)arg1;
- (BOOL)readPropertyFromTypeCode:(BOOL)arg1 bytes:(const char *)arg2 length:(unsigned long long)arg3;
- (void)writeToFileHandle:(struct __sFILE *)arg1;

@end

