/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCBuildPhaseDGSnapshot.h>

@class NSString;

@interface XCCopyFilesBuildPhaseDGSnapshot : XCBuildPhaseDGSnapshot
{
    int _dstSubfolderSpec;
    NSString *_dstPath;
}

+ (id)defaultName;
- (void)computeDependenciesForBuildFileReference:(id)arg1 inTargetBuildContext:(id)arg2;
- (void)dealloc;
- (id)destinationPath;
- (int)destinationSubfolder;
- (id)initWithInformationFromBuildPhase:(id)arg1 forTargetSnapshot:(id)arg2;

@end

