/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface XCCompatibilityFeature : NSObject
{
    NSString *_name;
}

+ (id)XCCodeSigningEntitlementsFeature;
+ (id)XCCodeSigningIdentityFeature;
+ (id)XCCodeSigningOtherFlagsFeature;
+ (id)XCCodeSigningResourceRulesPathFeature;
+ (id)XCCompositeSDKsFeature;
+ (id)XCDataModelVersionGroupsFeature;
+ (id)XCGCCCheckReturnValueOfOperatorNewFeature;
+ (id)XCGCCDisableStaticFunctionInliningFeature;
+ (id)XCGCCEnableFunctionInliningFeature;
+ (id)XCGCCEnableLinkingWithSharedLibrariesFeature;
+ (id)XCGCCGenerateFloatingPointLibraryCallsFeature;
+ (id)XCGCCGenerateIndirectFunctionCallsFeature;
+ (id)XCGCCGenerateRegisterSubroutineFunctionCallsFeature;
+ (id)XCGCCKernelDevelopmentModeFeature;
+ (id)XCGCCRecognizeBuiltinFunctionsFeature;
+ (id)XCGCCSetOutputFileSubtypeToAllFeature;
+ (id)XCGCCUseStandardIncludeSearchingFeature;
+ (id)XCMultipleProjectRootsFeature;
+ (id)XCParallelTargetBuildsFeature;
+ (id)XCPerArchitectureSettingsFeature;
+ (id)XCPerSDKSettingsFeature;
+ (id)XCProvisioningProfileFeature;
+ (id)XCWeakLinkFrameworkAttributeFeature;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)initWithName:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)name;

@end

