/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCPropertyDictionary.h>

@class XCPropertyConditionSet;

@interface XCConditionalPropertyDictionary : XCPropertyDictionary
{
    XCPropertyConditionSet *_conditionSet;
}

+ (id)dictionaryWithDictionary:(id)arg1;
- (long long)compare:(id)arg1;
- (id)conditionSet;
- (void)dealloc;
- (id)description;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)initWithConditionSet:(id)arg1;
- (BOOL)isConditional;
- (BOOL)matchesConditionSet:(id)arg1;

@end

