/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/PBXBookmark.h>

@class NSString;

@interface XCDiffFileBookmark : PBXBookmark
{
    NSString *_identifier;
    NSString *_defaultName;
}

+ (id)archivableAttributes;
+ (id)archiveNameForKey:(id)arg1;
+ (id)defaultWindowFrameAutosaveName;
- (void)dealloc;
- (id)defaultName;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithFileReference:(id)arg1;
- (id)initWithIdentifier:(id)arg1 andName:(id)arg2;
- (id)innerDescription;
- (BOOL)isEqual:(id)arg1;

@end

