/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet;

@interface XCDistributedBuildsSet : NSObject
{
    BOOL _currentlyUsed;
    id _name;
    NSMutableSet *_computers;
}

- (void)addComputer:(id)arg1;
- (void)addComputers:(id)arg1;
- (long long)caseInsensitiveCompare:(id)arg1;
- (id)computers;
- (BOOL)currentlyUsed;
- (void)dealloc;
- (id)description;
- (id)initWithName:(id)arg1 currentlyUsed:(BOOL)arg2;
- (id)name;
- (void)removeComputer:(id)arg1;
- (void)setCurrentlyUsed:(BOOL)arg1;
- (void)setName:(id)arg1;

@end

