/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface XCFileLocation : NSObject <NSCopying>
{
    NSString *_filePath;
    double _timestamp;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)filePath;
- (id)initFromDeserializer:(id)arg1;
- (id)initWithFilePath:(id)arg1;
- (double)timestamp;
- (void)writeToSerializer:(id)arg1;

@end

