/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCDependencyCommand.h>

@class NSMutableArray, NSString;

@interface XCFixLinkageCommand : XCDependencyCommand
{
    NSMutableArray *_additionalArguments;
    NSString *_compiledCodeFilePath;
    NSString *_outputFilePath;
}

- (void)addAdditionalArgument:(id)arg1;
- (id)additionalArguments;
- (id)arguments;
- (id)commandPath;
- (id)commandToolPath;
- (id)compiledCodeFilePath;
- (void)dealloc;
- (id)description;
- (id)descriptionForWorkQueueLog;
- (id)directoryPathToCreateBeforeProcessing;
- (id)initWithCommandPath:(id)arg1 compiledCodeFilePath:(id)arg2 outputFilePath:(id)arg3;
- (id)instantiatedCommandOutputParserWithLogSectionRecorder:(id)arg1;
- (BOOL)isReadyForProcessing;
- (id)name;
- (id)outputFilePath;
- (id)ruleInfo;
- (id)subprocessCommandLineForProcessing;

@end

