/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class XCFileSystemVNode, XCPath;

@interface XCFileSystemNode : NSObject
{
    XCPath *_path;
    unsigned long long _cacheGeneration;
    XCFileSystemVNode *_vnode;
    unsigned long long _numAssociates;
    id _associates;
}

+ (void)_registerStandardCachedFileInfoDerivationFunctionsIfNeeded;
+ (void *)cachedInfoDerivationFunctionForKeyNamed:(id)arg1;
+ (unsigned long long)currentCacheGeneration;
+ (void)discardCachedInfoForAllFiles;
+ (id)fileSystemNodeForPath:(id)arg1;
+ (void)incrementCacheGeneration;
+ (void)initialize;
+ (void)registerCachedInfoDerivationFunction:(void *)arg1 forKeyName:(id)arg2;
- (void)addAssociate:(id)arg1 ofType:(unsigned int)arg2;
- (id)associatesOfType:(unsigned int)arg1;
- (id)cachedValueForKey:(id)arg1;
- (id)childNodeWithName:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)descriptionOfAssociates;
- (void)discardCachedInfo;
- (void)discardCachedInfoAndAlsoParentDirectory:(BOOL)arg1;
- (void)discardCachedInfo_NoLock;
- (BOOL)existsInFileSystem;
- (id)fileType;
- (id)init;
- (id)initWithPath:(id)arg1;
- (BOOL)isDeletable;
- (BOOL)isWritable;
- (double)modificationTime;
- (id)parentNode;
- (id)path;
- (void)removeAllAssociates;
- (void)removeAssociate:(id)arg1;
- (void)removeAssociate:(id)arg1 ofType:(unsigned int)arg2;
- (void)removeAssociatesOfType:(unsigned int)arg1;
- (void)setCachedValue:(id)arg1 forKey:(id)arg2;
- (id)sortedDirectoryContents;
- (id)vnode;

@end

