/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface XCJavaCCPackageSymbol : NSObject
{
    NSString *name;
    int type;
    long long priority;
}

+ (id)symbolWithPartialName:(id)arg1 type:(int)arg2;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)initWithPartialName:(id)arg1 type:(int)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (id)partialName;
- (long long)priority;
- (void)setPriority:(long long)arg1;
- (int)symbolType;

@end

