/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface XCJavaIndexerTypeSpec : NSObject
{
    NSString *name;
    int tokenType;
    int dimension;
}

+ (id)typeSpecWithName:(id)arg1 dimension:(int)arg2;
+ (id)typeSpecWithTokenType:(int)arg1 dimension:(int)arg2;
- (void)dealloc;
- (id)description;
- (int)dimension;
- (id)initWithName:(id)arg1 dimension:(int)arg2;
- (id)initWithTokenType:(int)arg1 dimension:(int)arg2;
- (id)name;
- (void)setDimension:(int)arg1;
- (int)tokenType;

@end

