/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface XCObjectGraphPath : NSObject
{
    NSArray *_pathSegmentGIDs;
    NSArray *_pathSegmentNames;
}

- (id)copy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithSegmentGIDs:(id)arg1 names:(id)arg2;
- (id)pathByAddingSegmentWithGID:(id)arg1 name:(id)arg2;
- (id)pathSegmentGIDs;
- (id)pathSegmentNames;
- (unsigned long long)segmentCount;
- (id)segmentGIDAtIndex:(unsigned long long)arg1;
- (id)segmentNameAtIndex:(unsigned long long)arg1;
- (id)stringRepresentation;

@end

