/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCPosixTaskBackgroundThread.h>

@interface XCPosixTaskBackgroundWriterThread : XCPosixTaskBackgroundThread
{
}

- (void)backgroundThread:(id)arg1;
- (void)stopBackgroundThread;
- (void)writeData:(id)arg1;

@end

