/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSPortDelegate-Protocol.h"

@class NSError, NSObject<XCPosixTaskBackgroundParsing>, NSPort, NSRecursiveLock, XCPosixTaskBackgroundReaderThread, XCPosixTaskBackgroundWriterThread, XCPosixTaskLaunchInfo;

@interface XCPosixTask : NSObject <NSPortDelegate>
{
    int _taskPid;
    int _exitStatus;
    int _spawnResult;
    NSRecursiveLock *_lock;
    XCPosixTaskBackgroundWriterThread *_taskStdin;
    XCPosixTaskBackgroundReaderThread *_taskStdout;
    XCPosixTaskBackgroundReaderThread *_taskStderr;
    NSPort *_responseAvailableNotificationPort;
    NSObject *_observer;
    NSObject<XCPosixTaskBackgroundParsing> *_parser;
    XCPosixTaskLaunchInfo *_launchInfo;
    NSError *_lastError;
}

+ (void)initialize;
+ (void)selfTest;
- (void)_backgroundThreadExited:(id)arg1;
- (void)_backgroundThreadWillExit:(id)arg1;
- (void)_clearNotificationPort;
- (void)_enqueueObject:(id)arg1 inThread:(id)arg2 message:(int)arg3;
- (void)_posixError:(id)arg1 file:(char *)arg2 line:(int)arg3;
- (void)_postMessageToMainThread:(int)arg1 withData:(id)arg2;
- (void)_processReadQueue:(id)arg1 message:(SEL)arg2;
- (void)_requestExitNotification;
- (BOOL)_setupAndSpawn;
- (BOOL)_setupReadPipe:(int *)arg1 method:(int)arg2 descriptor:(int)arg3 path:(id)arg4;
- (BOOL)_setupStdin:(int *)arg1;
- (BOOL)_spawnTask:(const char *)arg1 inDirectory:(const char *)arg2 arguments:(const char **)arg3 environment:(const char **)arg4;
- (void)_thread:(id)arg1 receivedDataInBackground:(id)arg2;
- (BOOL)_wait:(BOOL)arg1;
- (void)_waitForExitInBackground:(id)arg1;
- (void)closeStdin;
- (void)dealloc;
- (void)deliverStderrObject:(id)arg1;
- (void)deliverStdoutObject:(id)arg1;
- (id)description;
- (void)error:(id)arg1;
- (int)exitStatus;
- (void)handlePortMessage:(id)arg1;
- (id)initWithLaunchInfo:(id)arg1;
- (void)interrupt;
- (void)kill;
- (id)lastError;
- (id)launchInfo;
- (void)outputComplete;
- (int)pid;
- (void)processTerminated;
- (void)receivedStderrObject:(id)arg1;
- (void)receivedStderrObjectInBackground:(id)arg1;
- (void)receivedStdoutObject:(id)arg1;
- (void)receivedStdoutObjectInBackground:(id)arg1;
- (void)signal:(int)arg1;
- (int)spawnResult;
- (void)terminate;
- (void)waitUntilExit;
- (void)writeData:(id)arg1;

@end

