/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCPropertyValue.h>

@class NSArray, NSString;

@interface XCPropertyMacroExpansionValue : XCPropertyValue
{
    NSString *_prefixString;
    XCPropertyValue *_macroNameValue;
    XCPropertyValue *_suffixValue;
    NSArray *_operators;
    unsigned short _delimChar;
}

- (void)assertInternalConsistency;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)evaluateAsStringInContext:(id)arg1 withNestingState:(const void *)arg2;
- (id)initWithPrefixString:(id)arg1 macroNameValue:(id)arg2 delimiterCharacter:(unsigned short)arg3 operators:(id)arg4 suffixValue:(id)arg5;
- (id)propertyValueDebugDescription;

@end

