/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "XCPropertyValues-Protocol.h"

@interface XCPropertyValue : NSObject <XCPropertyValues>
{
}

+ (void)initialize;
+ (id)propertyValueFromStringRepresentation:(id)arg1;
+ (id)propertyValueWithLookupOfProperty:(id)arg1;
- (id)arrayOfStringRepresentations;
- (void)assertInternalConsistency;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)evaluateAsStringInContext:(id)arg1;
- (id)evaluateAsStringInContext:(id)arg1 withNestingState:(const void *)arg2;
- (id)propertyValueDebugDescription;

@end

