/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCRefactoringTransformationSpecificLogic.h>

@interface XCRefactoringInlineFunctionSpecificLogic : XCRefactoringTransformationSpecificLogic
{
}

- (BOOL)getClass:(Class *)arg1 declaration:(id *)arg2 fromASTNode:(id)arg3 mainThreadArguments:(id)arg4 error:(id *)arg5;
- (id)localizedSnapshotTitle:(id)arg1;
- (id)preliminaryRelatedNames:(id)arg1;

@end

