/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, XCRefactoringParser;

@interface XCRefactoringMainThreadArguments : NSObject
{
    NSDictionary *_initialInput;
    XCRefactoringParser *_parser;
    NSDictionary *_userInput;
}

- (void)dealloc;
- (id)filePath;
- (id)initWithInitialInput:(id)arg1 parser:(id)arg2;
- (struct _XCRefactoringLineInfo)lineInfo;
- (id)parser;
- (id)project;
- (id)selectionSymbolInfo;
- (void)setUserInput:(id)arg1;
- (id)userInput;

@end

