/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSConditionLock, NSThread;

@interface XCRunLoopMonitor : NSObject
{
    NSThread *_monitoredThread;
    struct __CFRunLoopObserver *_runLoopWakeObserver;
    struct __CFRunLoopObserver *_runLoopSleepObserver;
    NSConditionLock *_runLoopStatus;
    double _sleepTime;
    NSThread *_lockingThread;
    unsigned long long _lockCount;
    unsigned long long _enabledCount;
}

+ (id)mainThreadMonitor;
- (BOOL)_currentThreadHasLock;
- (void)_runLoopWillRun;
- (void)_runLoopWillSleep;
- (void)_waitForIdleInterval:(double)arg1 blockMonitoredThread:(BOOL)arg2;
- (void)blockRunLoopAfterIdleInterval:(double)arg1;
- (void)dealloc;
- (void)disableMonitoring;
- (void)enableMonitoring;
- (id)init;
- (id)initWithThread:(id)arg1;
- (void)resumeRunLoop;
- (void)unblockRunLoop;
- (void)waitForRunLoopIdleInterval:(double)arg1;

@end

