/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSMutableDictionary;

@interface XCSCMReferenceDictionary : NSObject <NSCopying>
{
    NSMutableDictionary *_referenceDictionary;
}

+ (id)dictionaryForReferences:(id)arg1;
+ (id)parentFolderOfPaths:(id)arg1;
+ (BOOL)verifySingleParentFolderForPaths:(id)arg1;
- (unsigned long long)_countOfType:(id)arg1;
- (id)_dictionary;
- (id)_pathListsBasedOn:(id)arg1 withListSizeLimitedTo:(unsigned long long)arg2;
- (void)_removeObjectsWithType:(id)arg1;
- (void)_setDictionary:(id)arg1;
- (void)addReference:(id)arg1;
- (void)addReferencesFromArray:(id)arg1;
- (BOOL)areAllFiles;
- (BOOL)areAllFolders;
- (BOOL)areAllInSameFolder;
- (BOOL)areAllValid;
- (id)arrayOfAbsolutePaths;
- (id)arrayOfReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)count;
- (void)dealloc;
- (id)description;
- (BOOL)includesReferenceAtPath:(id)arg1;
- (id)init;
- (id)initWithReferences:(id)arg1;
- (id)pathListsDividedByParentFolder;
- (id)pathListsDividedByParentFolderWithListSizeLimitedTo:(long long)arg1;
- (id)pathListsDividedWithListSizeLimitedTo:(long long)arg1;
- (id)referenceForPath:(id)arg1;
- (void)removeAllFileReferences;
- (void)removeAllFolderReferences;
- (void)removeReferenceWithPath:(id)arg1;
- (void)removeReferencesForKeys:(id)arg1;
- (void)removeReferencesWithInvalidPaths;

@end

