/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "XCApplicationArchiver-Protocol.h"

@class DTExtension, NSArray, XCPlatformSpecification;

@interface XCSimpleApplicationArchiver : NSObject <XCApplicationArchiver>
{
    XCPlatformSpecification *_platform;
    DTExtension *_extension;
}

- (id)applicationIconURL;
- (_Bool)archiveApplicationAtURL:(id)arg1 error:(id *)arg2;
- (Class)detailViewControllerClass;
@property(retain) DTExtension *extension; // @synthesize extension=_extension;
- (id)initWithExtension:(id)arg1;
@property(retain) XCPlatformSpecification *platform; // @synthesize platform=_platform;
- (_Bool)willWriteArchiveInfo:(id)arg1 forApp:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly) NSArray *actionNames;

@end

