/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <DevToolsCore/XCOperation.h>

@class NSThread, XCMessageQueue;

@interface XCThreadedOperation : XCOperation
{
    XCMessageQueue *_messageQueue;
    NSThread *_runningThread;
}

- (void)_runOperationInBackground;
- (int)cleanupAfterRunning;
- (void)dealloc;
- (void)decodeOutputData:(id)arg1;
- (void)finalize;
- (void)handleAvailableObjectsOnMessageQueue:(id)arg1;
- (id)initWithIdentifier:(id)arg1;
- (void)performInvocationInOriginatingThread:(id)arg1;
- (void)postNotificationInOriginatingThread:(id)arg1;
- (int)runOperation;
- (int)runOperationInBackground;
- (id)runningThread;
- (void)sendDataToOutputStreamInOriginatingThread:(id)arg1;
- (void)setMessageDispatchSuspended:(BOOL)arg1;
- (int)setupBeforeRunning;

@end

